//
//  AgoraConfig.swift
//  Agora Sample
//
//  Created by shaun on 11/4/21.
//

import Foundation

// Note: in a production app this would be a bit more complex.
// Likely JSON would be used to store app id's depending on environment,
// and tokens would be loaded from a server. It is a good practice to
// centralize configuration so that downstream consumers do not have
// knowelege of where credential came from and are not concerned with this
struct AgoraConfig {
    static let sampleAppID = "4750b6ef198b45d8a1ea4631afc8c460"
    // using a sample RTM id to avoid having generating a token
    // would not be an issue in production with an auth server
    static let sampleAppIDRTM = "4750b6ef198b45d8a1ea4631afc8c460"

    // These following are variables that are generated by the Agora control panel, every day of development
    // they need to be changed, normally this would be handled by internal server handling of this. But that
    // is outside of the scope of this project.
    // NOTE: needs to be updated everyday!
    static let testingToken: String? = nil
    static let testingChannel = "Testing"
}
